### ISSUE TITLE
MAP entry modal, bugs returned??

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#76] opened 2017-03-27 18:22 UTC
Appears to find 1 route, when there shouldn't be any.

Changing CC doesn't stick.  changed CA to AR but on reload reverted to CA
![pastedgraphic-26](https://cloud.githubusercontent.com/assets/12848029/24371064/80600e50-12de-11e7-93dd-dcae467860a3.png)

Lost auto complete in Contrib filed

Possibly performance issue on my end??

**Comment by Andrew-Clement** [comment] 2017-03-27 18:46
Also, appears checked conditions with zero are excluded from join
![pastedgraphic-27](https://cloud.githubusercontent.com/assets/12848029/24372110/c2e4d974-12e1-11e7-86e0-e9b7f4f6d949.png)

In cases mentioned above where the actual result should be zero, but it reports one route found and the MAP ROUTES FOUND button is blue, clicking it gets the correct response 
![pastedgraphic-28](https://cloud.githubusercontent.com/assets/12848029/24372400/b3725b0a-12e2-11e7-831c-d8bbc3d8ff46.png)

**Comment by agamba** [comment] 2017-03-28 00:28
This should be fixed now. Please re-test same case

**Comment by agamba** [comment] 2017-03-28 00:42
Conditions with zero results are excluded by default. I think we need automatically un-check those boxes for those cases. OR, we leave it to the user? Please advice

**Comment by agamba** [comment] 2017-03-28 00:43
removing criteria = zero from the calculation of total routes is MUST on the server side. just to let you know..

**Comment by Andrew-Clement** [comment] 2017-03-28 01:40
> Conditions with zero results are excluded by default. I think we need automatically un-check those boxes for those cases
YES.automatically un-check  Don't leave it to user as it is  inconsistent with **Number of routes found that meet all the above _checked_ conditions**

**Comment by colinmccann** [comment] 2017-06-20 12:00
@Andrew-Clement can we close this?

**Comment by Andrew-Clement** [comment] 2017-06-21 10:01
No, problem persists.

If no routes for a condition, box should be un-checked


On 2017-06-20, at 1:00 PM, colinmccann <notifications@github.com> wrote:

@Andrew-Clement can we close this?

**Comment by colinmccann** [comment] 2017-06-22 07:52
I may be misunderstanding something here... this is what I see on my end. What else needs to be unchecked?
<img width="1170" alt="screen shot 2017-06-22 at 2 50 57 pm" src="https://user-images.githubusercontent.com/754840/27422970-41b287d0-575a-11e7-8e99-3b110c0ece0d.png">

**Comment by Andrew-Clement** [comment] 2017-06-22 09:01
See the Mar 27 comment above.

The line with You appear to be near Rome gives 0 routes but the box is checked. Simply un-check the box if the results are 0

**Comment by colinmccann** [comment] 2017-06-22 09:42
So I guess the uncheck issue relates only to the location fields? (and not eg ISP). This definitely makes it harder to test :/   either way, this is likely best handled by @agamba , I believe

**Comment by colinmccann** [comment] 2017-06-22 09:58
Since I was curious, I dug into the code around this. This opening modal is very complex, however everything looks correct to me (in regards to unchecking). I did my best to test it by modifying variables to simulate that I was in a location with no routes, and it unchecked as intended. @Andrew-Clement , can you please reconfirm?

**Comment by Andrew-Clement** [comment] 2017-06-22 10:20
Yes, it worked as intended on first entry, but if I recall, if on entry the inferred city produces a non-zero result, but one then corrects the location  producing a zero result, the boz stays checked.  Something like that.  I can't reproduce this now since my currently inferred location in both Map entry and the Client (Blackburn UK), is not the one recorded with the TR (aarrghh) and hence found through the DB query, which produces a zero initial result.  Convoluted, picky and only a minor edge case, so best drop for now.

**Closed** 2017-06-22 10:20 UTC
Labels: bug
